[project]
authors = ["Emmanuelle Sarrazin <emmanuelle.sarrazin@cnes.fr>"]
channels = ["conda-forge"]
description = "Dask tutorial"
name = "dask-tutorial"
platforms = ["win-64", "linux-64", "osx-64", "osx-arm64"]
version = "0.1.0"

[tasks]

[dependencies]
python = "3.12.*"
pip = ">=25.0,<26"
jupyterlab = ">=4.3.5,<5"
matplotlib = ">=3.10.0,<4"
xarray = ">=2025.1.2,<2026"
dask = ">=2025.2.0,<2026"
scikit-learn = ">=1.6.1,<2"
python-graphviz = ">=0.20.3,<0.21"
graphviz = ">=12.2.1,<13"
ipycytoscape = ">=1.3.3,<2"
zarr = ">=3.0.3,<4"
pooch = ">=1.8.2,<2"
dask-ml = "==2025.1.0"
cryptography = ">=44.0.1,<45"

