name: dask-tutorial
channels:
  - conda-forge
dependencies:
  - python=3.10
  - jupyterlab
  - numpy
  - scipy
  - bokeh=2.4
  - dask=2023.12.0
  - dask-labextension
  - distributed=2023.12.0
  - matplotlib
  - pandas
  - pip
  - python-graphviz
  - ipycytoscape
  - pyarrow
  - s3fs
  - zarr
  - pooch
  - xarray
  - mamba
  - scikit-learn
  - dask-ml
